easy_admin:
    site_name: 'Скоринг'
    design:
        menu:
            - { label: 'Администрирование', route: 'easyadmin' }
            - { label: 'Регистрация', route: 'user_register' }
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            label: 'Пользователь'
            form:
                fields:

                    - { property: 'last_name', 'label': 'Фамилия'}
                    - { property: 'first_name', 'label': 'Имя'}
                    - { property: 'email', type: 'email', 'label': 'E-mail' }
                    - { property: 'phone', type: 'tel', 'label': 'Телефон' }
                    - { property: 'grade', type: 'App\Form\RegisterType\GradeType', 'label': 'Образование'}
                    - { property: 'personal_data', 'label': 'Согласен с условиями'}
            list:
                actions: ['show', 'delete']
                title: 'Список пользователей'
                fields:
                    - id
                    - { property: 'last_name', 'label': 'Фамилия'}
                    - { property: 'first_name', 'label': 'Имя'}
                    - { property: 'email', type: 'email', 'label': 'E-mail' }
                    - { property: 'phone', type: 'tel', 'label': 'Телефон' }
                    - { property: 'grade', template: 'admin/list_grade.html.twig', 'label': 'Образование'}
                    - { property: 'score', 'label': 'Скоринг'}
                    - { property: 'personal_data', 'label': 'Согласен с условиями'}
            show:
                fields:
                    - id
                    - { property: 'last_name', 'label': 'Фамилия'}
                    - { property: 'first_name', 'label': 'Имя'}
                    - { property: 'email', type: 'email', 'label': 'E-mail' }
                    - { property: 'phone', type: 'tel', 'label': 'Телефон' }
                    - { property: 'grade', template: 'admin/list_grade.html.twig', 'label': 'Образование'}
                    - { property: 'score', 'label': 'Скоринг'}
                    - { property: 'personal_data', 'label': 'Согласен с условиями'}
